### ISSUE TITLE
"Floating point exception" crash inf demo_lce.py if no objects detected

### ISSUE THREAD

**Issue by nathankopp** [tehtea/QuickYOLO#2]
When running demo_lce.py, if no boxes are detected, I receive "Floating point exception" on the screen and the  program crashes immediately.

It appears that this is NOT a Python exception, but rather it is a C++ exception.  It seems to be happening during the call to "self.interpreter.predict(input_image)".  This function is defined in Larq compute-engine (not QuickYOLO) in the file larq_compute_engine/tflite/interpreter_wrapper_utils.h

The error is happening in the call to "interpreter_->Invoke();"  I tried adding a "try{}catch(...){}" block around the call to "Invoke()", but the execution still stops inside Invoke().

Any ideas?

**Comment by tehtea** [comment]
Thanks for reporting this issue so comprehensively! I managed to reproduce this too and while its not a Python exception, I think the temporary workaround is to change the postprocessing function such that box filtering is only done in the demo application. However, the model will still return the indexes for selected boxes and their new scores after applying soft-nms.

Take a pull from the main branch again and see if the problem goes away?

**Comment by nathankopp** [comment]
That worked. Thanks!

While waiting for this fix, I tested using TensorFlow instead of TFlite/LCE, by using the code in detection_demo() and yolov3/utils.py.  In doing this, I discovered that there seems to be some duplicated code logic that probably should be merged into one:

- TensorFlow version: yolov3/utils.py detect_image(), postprocess_boxes(), nms()
- TFLite/LCE version: export_larq_model.py PostProcess()

Because of the two different versions, it is likely that the TensorFlow and the TFLite/LCE versions will produce different results. I think it might be nice to refactor this code so that both TensorFlow and TFLite/LCE share the same Python code for these aspects of the logic.

**Comment by tehtea** [comment]
Yup you’re right, in general there is a lot of room for refactoring in this repo, but this is important because it seems like postprocessing is used in mAP calculation so it’s even more important to ensure that it is consistent in both TF and LCE. Will be pushing the patch to unify them soon!
